function turns(keyInput, gridInstance, t, startInstance)
    if strcmp(t.Running, 'off')
        start(t); % Start the timer
        startInstance.start = datetime('now');
    end
    switch keyInput
            % % old method before I realized there was a more efficient way
            % % am keeping this section in in case I return to the project
            % later and see a need for it

            % rect1 = gridInstance.Squares{6, i, 3};
            % rect2 = gridInstance.Squares{2, i, 3};
            % rect3 = gridInstance.Squares{5, i, 3};
            % rect4 = gridInstance.Squares{4, i, 1};
            
            % % Get the current colors of the rectangles
            % color1 = rect1.FaceColor;
            % color2 = rect2.FaceColor;
            % color3 = rect3.FaceColor;
            % color4 = rect4.FaceColor;
            
            % % Cycle the colors
            % rect1.FaceColor = color2;
            % rect2.FaceColor = color3;
            % rect3.FaceColor = color4;
            % rect4.FaceColor = color1;
            
        case 'space'
            % spacebar to scramble up the cube, as an alternative to
            % pressing the on-screen button
            for i = 1:20
                moves = ['s','d','f','g','h','j','k','l','w','e','i','o'];
                turns(moves(randperm(12, 1)), gridInstance, t, startInstance); % do a random turn based on the selected move
            end

        case 'return'
            stop(t); % Stop the timer if "enter" is pressed"
           
        case 'k'
            % Turn the right-hand side counterclockwise
            for i = 1:3
                [gridInstance.Squares{4, 4-i, 1}.FaceColor, ...
                 gridInstance.Squares{5, i, 3}.FaceColor, ...
                 gridInstance.Squares{2, i, 3}.FaceColor, ...
                 gridInstance.Squares{6, i, 3}.FaceColor] = ...
                 deal(gridInstance.Squares{5, i, 3}.FaceColor, ...
                  gridInstance.Squares{2, i, 3}.FaceColor, ...
                  gridInstance.Squares{6, i, 3}.FaceColor, ...
                  gridInstance.Squares{4, 4-i, 1}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{3, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{3, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{3, 3, j}.FaceColor, ...
                gridInstance.Squares{3, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{3, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{3, 3, j}.FaceColor, ...
                gridInstance.Squares{3, j, 1}.FaceColor, ...
                gridInstance.Squares{3, 1, 4-j}.FaceColor);
            end
            
        case 'i'
            % Turn the right-hand side clockwise
            for i = 1:3
                [gridInstance.Squares{4, 4-i, 1}.FaceColor, ...
                 gridInstance.Squares{5, i, 3}.FaceColor, ...
                 gridInstance.Squares{2, i, 3}.FaceColor, ...
                 gridInstance.Squares{6, i, 3}.FaceColor] = ...
                 deal(gridInstance.Squares{6, i, 3}.FaceColor, ...
                  gridInstance.Squares{4, 4-i, 1}.FaceColor, ...
                  gridInstance.Squares{5, i, 3}.FaceColor, ...
                  gridInstance.Squares{2, i, 3}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{3, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{3, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{3, 3, j}.FaceColor, ...
                gridInstance.Squares{3, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{3, j, 1}.FaceColor, ...
                gridInstance.Squares{3, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{3, 4-j, 3}.FaceColor,...
                gridInstance.Squares{3, 3, j}.FaceColor);
            end
            
        case 'e'
            % Turn the left-hand side counterclockwise
            for i = 1:3
                [gridInstance.Squares{4, 4-i, 3}.FaceColor, ...
                 gridInstance.Squares{5, i, 1}.FaceColor, ...
                 gridInstance.Squares{2, i, 1}.FaceColor, ...
                 gridInstance.Squares{6, i, 1}.FaceColor] = ...
                 deal(gridInstance.Squares{6, i, 1}.FaceColor, ...
                  gridInstance.Squares{4, 4-i, 3}.FaceColor, ...
                  gridInstance.Squares{5, i, 1}.FaceColor, ...
                  gridInstance.Squares{2, i, 1}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{1, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{1, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{1, 3, j}.FaceColor, ...
                gridInstance.Squares{1, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{1, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{1, 3, j}.FaceColor, ...
                gridInstance.Squares{1, j, 1}.FaceColor, ...
                gridInstance.Squares{1, 1, 4-j}.FaceColor);
            end

        case 'd'
            % Turn the left-hand side clockwise
            for i = 1:3
                [gridInstance.Squares{4, 4-i, 3}.FaceColor, ...
                 gridInstance.Squares{5, i, 1}.FaceColor, ...
                 gridInstance.Squares{2, i, 1}.FaceColor, ...
                 gridInstance.Squares{6, i, 1}.FaceColor] = ...
                 deal(gridInstance.Squares{5, i, 1}.FaceColor, ...
                  gridInstance.Squares{2, i, 1}.FaceColor, ...
                  gridInstance.Squares{6, i, 1}.FaceColor, ...
                  gridInstance.Squares{4, 4-i, 3}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{1, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{1, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{1, 3, j}.FaceColor, ...
                gridInstance.Squares{1, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{1, j, 1}.FaceColor, ...
                gridInstance.Squares{1, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{1, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{1, 3, j}.FaceColor);
            end

        case 'f'
            % Turn the upper-hand side counterclockwise
            for i = 1:3
                [gridInstance.Squares{1, 1, i}.FaceColor, ...
                 gridInstance.Squares{2, 1, i}.FaceColor, ...
                 gridInstance.Squares{3, 1, i}.FaceColor, ...
                 gridInstance.Squares{4, 1, i}.FaceColor] = ...
                 deal(gridInstance.Squares{4, 1, i}.FaceColor, ...
                  gridInstance.Squares{1, 1, i}.FaceColor, ...
                  gridInstance.Squares{2, 1, i}.FaceColor, ...
                  gridInstance.Squares{3, 1, i}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{6, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{6, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{6, 3, j}.FaceColor, ...
                gridInstance.Squares{6, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{6, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{6, 3, j}.FaceColor, ...
                gridInstance.Squares{6, j, 1}.FaceColor, ...
                gridInstance.Squares{6, 1, 4-j}.FaceColor);
            end
            
        case 'j'
            % Turn the upper-hand side clockwise
            for i = 1:3
                [gridInstance.Squares{1, 1, i}.FaceColor, ...
                 gridInstance.Squares{2, 1, i}.FaceColor, ...
                 gridInstance.Squares{3, 1, i}.FaceColor, ...
                 gridInstance.Squares{4, 1, i}.FaceColor] = ...
                 deal(gridInstance.Squares{2, 1, i}.FaceColor, ...
                  gridInstance.Squares{3, 1, i}.FaceColor, ...
                  gridInstance.Squares{4, 1, i}.FaceColor, ...
                  gridInstance.Squares{1, 1, i}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{6, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{6, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{6, 3, j}.FaceColor, ...
                gridInstance.Squares{6, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{6, j, 1}.FaceColor, ...
                gridInstance.Squares{6, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{6, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{6, 3, j}.FaceColor);
            end

        case 'l'
            % Turn the down-hand side counterclockwise
            for i = 1:3
                [gridInstance.Squares{1, 3, i}.FaceColor, ...
                 gridInstance.Squares{2, 3, i}.FaceColor, ...
                 gridInstance.Squares{3, 3, i}.FaceColor, ...
                 gridInstance.Squares{4, 3, i}.FaceColor] = ...
                 deal(gridInstance.Squares{2, 3, i}.FaceColor, ...
                  gridInstance.Squares{3, 3, i}.FaceColor, ...
                  gridInstance.Squares{4, 3, i}.FaceColor, ...
                  gridInstance.Squares{1, 3, i}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{5, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{5, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{5, 3, j}.FaceColor, ...
                gridInstance.Squares{5, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{5, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{5, 3, j}.FaceColor, ...
                gridInstance.Squares{5, j, 1}.FaceColor, ...
                gridInstance.Squares{5, 1, 4-j}.FaceColor);
            end
            
        case 's'
            % Turn the down-hand side clockwise
            for i = 1:3
                [gridInstance.Squares{1, 3, i}.FaceColor, ...
                 gridInstance.Squares{2, 3, i}.FaceColor, ...
                 gridInstance.Squares{3, 3, i}.FaceColor, ...
                 gridInstance.Squares{4, 3, i}.FaceColor] = ...
                 deal(gridInstance.Squares{4, 3, i}.FaceColor, ...
                  gridInstance.Squares{1, 3, i}.FaceColor, ...
                  gridInstance.Squares{2, 3, i}.FaceColor, ...
                  gridInstance.Squares{3, 3, i}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{5, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{5, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{5, 3, j}.FaceColor, ...
                gridInstance.Squares{5, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{5, j, 1}.FaceColor, ...
                gridInstance.Squares{5, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{5, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{5, 3, j}.FaceColor);
            end
        case 'g'
            % Turn the front-hand side counterclockwise
            for i = 1:3
                [gridInstance.Squares{6, 3, i}.FaceColor, ...
                 gridInstance.Squares{3, i, 1}.FaceColor, ...
                 gridInstance.Squares{5, 1, 4-i}.FaceColor, ...
                 gridInstance.Squares{1, 4-i, 3}.FaceColor] = ...
                 deal(gridInstance.Squares{3, i, 1}.FaceColor, ...
                  gridInstance.Squares{5, 1, 4-i}.FaceColor, ...
                  gridInstance.Squares{1, 4-i, 3}.FaceColor, ...
                  gridInstance.Squares{6, 3, i}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{2, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{2, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{2, 3, j}.FaceColor, ...
                gridInstance.Squares{2, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{2, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{2, 3, j}.FaceColor, ...
                gridInstance.Squares{2, j, 1}.FaceColor, ...
                gridInstance.Squares{2, 1, 4-j}.FaceColor);
            end
            
        case 'h'
            % Turn the front-hand side clockwise
            for i = 1:3
                [gridInstance.Squares{6, 3, i}.FaceColor, ...
                 gridInstance.Squares{3, i, 1}.FaceColor, ...
                 gridInstance.Squares{5, 1, 4-i}.FaceColor, ...
                 gridInstance.Squares{1, 4-i, 3}.FaceColor] = ...
                 deal(gridInstance.Squares{1, 4-i, 3}.FaceColor, ...
                  gridInstance.Squares{6, 3, i}.FaceColor, ...
                  gridInstance.Squares{3, i, 1}.FaceColor, ...
                  gridInstance.Squares{5, 1, 4-i}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{2, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{2, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{2, 3, j}.FaceColor, ...
                gridInstance.Squares{2, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{2, j, 1}.FaceColor, ...
                gridInstance.Squares{2, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{2, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{2, 3, j}.FaceColor);
            end

        case 'o'
            % Turn the back-hand side counterclockwise
            for i = 1:3
                [gridInstance.Squares{6, 1, i}.FaceColor, ...
                 gridInstance.Squares{3, i, 3}.FaceColor, ...
                 gridInstance.Squares{5, 3, 4-i}.FaceColor, ...
                 gridInstance.Squares{1, 4-i, 1}.FaceColor] = ...
                 deal(gridInstance.Squares{1, 4-i, 1}.FaceColor, ...
                  gridInstance.Squares{6, 1, i}.FaceColor, ...
                  gridInstance.Squares{3, i, 3}.FaceColor, ...
                  gridInstance.Squares{5, 3, 4-i}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{4, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{4, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{4, 3, j}.FaceColor, ...
                gridInstance.Squares{4, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{4, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{4, 3, j}.FaceColor, ...
                gridInstance.Squares{4, j, 1}.FaceColor, ...
                gridInstance.Squares{4, 1, 4-j}.FaceColor);
            end
            
        case 'w'
            % Turn the back-hand side clockwise
            for i = 1:3
                [gridInstance.Squares{6, 1, i}.FaceColor, ...
                 gridInstance.Squares{3, i, 3}.FaceColor, ...
                 gridInstance.Squares{5, 3, 4-i}.FaceColor, ...
                 gridInstance.Squares{1, 4-i, 1}.FaceColor] = ...
                 deal(gridInstance.Squares{3, i, 3}.FaceColor, ...
                  gridInstance.Squares{5, 3, 4-i}.FaceColor, ...
                  gridInstance.Squares{1, 4-i, 1}.FaceColor, ...
                  gridInstance.Squares{6, 1, i}.FaceColor);
            end
            for j = 1:2
                [gridInstance.Squares{4, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{4, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{4, 3, j}.FaceColor, ...
                gridInstance.Squares{4, j, 1}.FaceColor] = ...
                deal(gridInstance.Squares{4, j, 1}.FaceColor, ...
                gridInstance.Squares{4, 1, 4-j}.FaceColor, ...
                gridInstance.Squares{4, 4-j, 3}.FaceColor, ...
                gridInstance.Squares{4, 3, j}.FaceColor);
            end
            
        otherwise
            disp(keyInput)
    end
end